# listen
port: ":8080"

# database
db:
  mode: "sqlite" # sqlite、 mysql、 postgres
  dsn: "dataserver.db" # Data Source Name

#email:
#  host: smtp.gmail.com
#  port: 587
#  user: dev@redeslab.io
#  pwd: thop24680

email:
  host: smtp.qq.com
  port: 465
  user: 342529499@qq.com
  pwd: guzqxmphgdlfbhjg

# rabbit mq
rabbitmq: 

jwt:
  secret:

# price
price:
  mop: 0xcc07B6277c7B4614884eEa59972AfEa17f40716F
  usdt: 0x804c7762fbeab64ac554aec644e43ab934d23ff0
  receiptor: 0x5529E3F428f42C23DDaCbb80fd46247B775725b1
  traffic: 0.0001 # download price
  storage: 0.0001 # upload price

# download base url
gateway: https://gateway.mopweb3.cn/

bsc:
  rpc: http://202.83.246.155:8575
  browser: https://testnet.bscscan.com/

alipay:
  appid: 2021000122621871
  privateKey:
  isProd:
  returnUrl:
  notifyUrl:
  alipayPublicKeyContent: